[reference](https://docs.scipy.org/doc/numpy/reference/index.html)

### Creating NumPy arrays
https://docs.scipy.org/doc/numpy/reference/routines.array-creation.html

In [2]:
import numpy as np
#list to 1d array
print np.array([1,2,3])

#list of tuples to 2D array
print np.array([(1,2,3),(2,3,4)])

[1 2 3]
[[1 2 3]
 [2 3 4]]


In [24]:
lis=[1,2,3,4,5,6]
np.array(lis).reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

### Arrays with initial values

In [5]:
#empty array-random float values
print np.empty(5)
print np.empty((5,4))
#array of 1s
print np.ones((2,2))
#array of 0s
print np.zeros((2,3))


[  0.00000000e+000  -1.29074467e-231   1.97626258e-323   0.00000000e+000
   0.00000000e+000]
[[  0.00000000e+000   0.00000000e+000   6.95016100e-310   1.27319747e-313]
 [  1.27319747e-313   1.27319747e-313   2.12199579e-314   1.91976497e-313]
 [  2.22095715e-314   2.75859453e-313   5.45352918e-311   3.60739284e-313]
 [  0.00000000e+000   0.00000000e+000  -1.29074467e-231   0.00000000e+000]
 [  8.90030504e-307   5.91523870e-302   6.95016100e-310   1.39067338e-308]]
[[ 1.  1.]
 [ 1.  1.]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]]


### Specify the datatype
https://docs.scipy.org/doc/numpy/user/basics.types.html

In [6]:
print np.ones((2,3),dtype=np.int_)

[[1 1 1]
 [1 1 1]]


### Generating random numbers
[random sampling](https://docs.scipy.org/doc/numpy/reference/routines.random.html)

In [12]:
#generate an array full of random numbers,uniformly samled from [0,1]
print np.random.random((1,2))
#Like random, but slightly different syntax
print np.random.rand(1,2)
#sample numbers from a Gaussian distribution
print np.random.normal(50,10,size=(1,3)) #mean=50 std=10

[[ 0.23480979  0.87781729]]
[[ 0.78817145  0.61242519]]
[[ 38.54577997  35.13992966  69.08513085]]


In [3]:
#random integers
print np.random.randint(10)# a single integer in [0,10)
print np.random.randint(0,10)#same as above, specify [low,high) explicit
print np.random.randint(0,10,size=5)#5 random integers as an 1D array
print np.random.randint(0,10,size=(2,3))#2*3 array of random int

6
2
[7 0 0 3 0]
[[1 7 4]
 [9 9 9]]


### Array attributes

In [3]:
a=np.random.random((3,2))
print a
print a.shape   #shape of array
print a.shape[0]#num of rows
print a.shape[1]#num of cols

[[ 0.93061501  0.47697677]
 [ 0.9459022   0.39276045]
 [ 0.97643153  0.32764182]]
(3, 2)
3
2


In [26]:
print len(a.shape)#num of dimension
print a.ndim      #num of dimension

2
2


In [17]:
print a.size #num of elements 3*2
print a.dtype #data type of elements

6
float64


### Operations on ndarrays
+ [mathematical function](https://docs.scipy.org/doc/numpy/reference/routines.math.html)  
+ [statistics](https://docs.scipy.org/doc/numpy/reference/routines.statistics.html)

In [6]:
np.random.seed(693)
a=np.random.randint(0,10,size=(5,2))
print a

[[2 0]
 [5 1]
 [1 3]
 [4 4]
 [9 2]]


In [5]:
print a.sum()
print a.sum(axis=0) #sum along rows
print a.sum(axis=1) #sum along columns

31
[21 10]
[ 2  6  4  8 11]


In [33]:
print a.max()
print a.mean(axis=0)

9
[ 5.   3.   5.   2.8]


### Locate maximum value
[Sorting, searching, and counting](https://docs.scipy.org/doc/numpy/reference/routines.sort.html)

In [38]:
a = np.array([9, 6, 2, 3, 12, 14, 7, 10], dtype=np.int32).reshape(2,-1)  # 32-bit integer array
print a
print "Maximum value:", a.max()
print "Index of max.:", a.argmax(axis=1)

[[ 9  6  2  3]
 [12 14  7 10]]
Maximum value: 14
Index of max.: [0 1]


### Timing python operations

In [42]:
import time
t1=time.time()
print 'test'
t2=time.time()
print 'The time taken by print statement is',round(t2-t1,5),'s'

test
The time taken by print statement is 0.00073 s


### Accessing array elements

[index](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html)  
**Note: Indexing starts at 0 (zero).**

-0123  
0  
1  
2  
3  

+ nd1[row,col]
+ nd1[0:3,1:3] the last value 3 is not included
+ nd1[:,3] all rows, column 3. 
+ nd1[-2,1:3] .  the last 1&2 row, 1&2 column

In [45]:
a=np.random.rand(5,4)
print a
#access element at position (3,2)
print a[3,2]
#access elements in defined range
print a[0,1:3]

[[ 0.56136226  0.80309824  0.02816901  0.34656847]
 [ 0.52476857  0.7780763   0.2852825   0.09296586]
 [ 0.18428266  0.27587949  0.01893441  0.96264274]
 [ 0.44672924  0.05898629  0.11829386  0.45481583]
 [ 0.41412521  0.214972    0.72249968  0.61072672]]
0.118293862338
[ 0.80309824  0.02816901]


In [46]:
#Slice 
#n:m:t specifies a range that starts at n, and stops before m,in steps of size t
print a[:,0:3:2] #col 0,2;skip col 1

[[ 0.56136226  0.02816901]
 [ 0.52476857  0.2852825 ]
 [ 0.18428266  0.01893441]
 [ 0.44672924  0.11829386]
 [ 0.41412521  0.72249968]]


### Modifying array elements

In [49]:
#assign a value to a particular location
a[0,0]=1
print 'Modified a (replace the first value):\n',a

Modified a(replace the first value):
[[ 1.          0.80309824  0.02816901  0.34656847]
 [ 0.52476857  0.7780763   0.2852825   0.09296586]
 [ 0.18428266  0.27587949  0.01893441  0.96264274]
 [ 0.44672924  0.05898629  0.11829386  0.45481583]
 [ 0.41412521  0.214972    0.72249968  0.61072672]]


In [50]:
#assign a value to the entire row
a[0,:]=2
print 'Modified a (replace a row witha single value):\n',a

Modified a (replace a row witha single value):
[[ 2.          2.          2.          2.        ]
 [ 0.52476857  0.7780763   0.2852825   0.09296586]
 [ 0.18428266  0.27587949  0.01893441  0.96264274]
 [ 0.44672924  0.05898629  0.11829386  0.45481583]
 [ 0.41412521  0.214972    0.72249968  0.61072672]]


In [51]:
#assign a list to a column in an array
a[:,3]=[1,2,3,4,5]
print 'Modified a (replace a row witha single value):\n',a

Modified a (replace a row witha single value):
[[ 2.          2.          2.          1.        ]
 [ 0.52476857  0.7780763   0.2852825   2.        ]
 [ 0.18428266  0.27587949  0.01893441  3.        ]
 [ 0.44672924  0.05898629  0.11829386  4.        ]
 [ 0.41412521  0.214972    0.72249968  5.        ]]


### Indexing An Array With Another Array
[integer array index](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html#integer-array-indexing)

In [8]:
#access using ist of indices
a=np.random.rand(5)
indices=[1,1,2,3]
print a,'\n',a[indices]

[ 0.54253067  0.00875843  0.36469785  0.45897155  0.88777042] 
[ 0.00875843  0.00875843  0.36469785  0.45897155]


### Boolean or "mask" index arrays
[Boolean array indexing](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html#boolean-array-indexing)  
Now, when this is used to index the array a,   
only those positions are selected where there is a True,   
and the values are collected into a list.

In [63]:
a=np.array([[1,2,3,4,5],[1,2,3,4,5]])
mean=a.mean()
#masking
print a<mean
print a[a<mean]

a[a<mean]= mean #replace the less than mean elements with mean
print a

[[ True  True False False False]
 [ True  True False False False]]
[1 2 1 2]
[[3 3 3 4 5]
 [3 3 3 4 5]]


In [64]:
x = np.array([[1., 2.], [np.nan, 3.], [np.nan, np.nan]])
print x
print x[~np.isnan(x)]


[[  1.   2.]
 [ nan   3.]
 [ nan  nan]]
[ 1.  2.  3.]


### [Arithmetic operations](https://docs.scipy.org/doc/numpy/reference/routines.math.html#arithmetic-operations)
[matrix](https://docs.scipy.org/doc/numpy/reference/generated/numpy.matrix.html) class and the
[linear algebra](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

+ numpy.add: Element-wise addition, same as + operator
+ numpy.subtract: Element-wise subtraction, same as -
+ numpy.multiply: Element-wise multiplication, same as *
+ numpy.divide: Element-wise division, same as /
+ numpy.dot: Dot product (1D arrays), matrix multiplication (2D)


In [75]:
a=np.array([[1,2,3,4,5],[10,20,30,40,50]]) #2*5
b=np.array([[100,100,100,100,100],[1,1,1,1,1]])
print np.add(a,b),'\n'

print np.dot(a,b.reshape(5,2)),'\n'

print a+b

[[101 102 103 104 105]
 [ 11  21  31  41  51]] 

[[ 609  312]
 [6090 3120]] 

[[101 102 103 104 105]
 [ 11  21  31  41  51]]
