In [5]:
>>> from sklearn.preprocessing import scale,StandardScaler
>>> import numpy as np
>>> X = np.array([[ 1., -1.,  2.],
                   [ 2.,  100,  200],
                   [ 0.,  1., -1.]])
X_scaled=scale(X, with_mean=True, with_std=True)
#center the data before scaling   scale the data to unit variance 
X_scaled

array([[ 0.        , -0.72821076, -0.6910984 ],
       [ 1.22474487,  1.41400148,  1.41409365],
       [-1.22474487, -0.68579072, -0.72299525]])

In [7]:
scaler=StandardScaler(with_mean=True, with_std=True)
scaler.fit(X)
X_scaled=scaler.transform(X)
print X_scaled

[[ 0.         -0.72821076 -0.6910984 ]
 [ 1.22474487  1.41400148  1.41409365]
 [-1.22474487 -0.68579072 -0.72299525]]
