In [11]:
>>> from sklearn.cluster import KMeans
>>> import numpy as np
>>> X = np.array([[1, 2], [1, 4], [1, 0],\
                 [4, 2], [4, 4], [4, 0]]) #2D array
>>> kmeans = KMeans(n_clusters=2, max_iter=200,n_init=5).fit(X)

>>> print kmeans.cluster_centers_# centroid place
>>> print kmeans.labels_ #labels of training data
>>> print kmeans.inertia_
#predict after having labels
print ' '
>>> print kmeans.predict([[-10,-9],[0, 0], [4, 4],[10,10]])

print ' '
print kmeans.transform(X)#Transform X to a cluster-distance space


[[ 4.  2.]
 [ 1.  2.]]
[1 1 1 0 0 0]
16.0
 
[1 1 0 0]
 
[[ 3.          0.        ]
 [ 3.60555128  2.        ]
 [ 3.60555128  2.        ]
 [ 0.          3.        ]
 [ 2.          3.60555128]
 [ 2.          3.60555128]]
